### ISSUE TITLE
Weird behavior when using floating window 

### ISSUE THREAD

**Issue by DjEvCreeperX** [sunshine0523/Mi-Freeform#10]
When I try to use the floating window with another app in fullscreen and I tap the fullscreen application the floating window gets "frozen" and it stops running until I tap it again. Is there any way to fix this?
Edit: My device is a Motorola Z2 Force running android 9 with LSPosed and sui enabled

**Comment by Likver** [comment]
Same problem, when i touch the app window (the app itself, not the floating window buttons like closing the window, moving it etc) it just freezes the entire screen and after some seconds the app crashes (mi-freeform app) 
Device: Xperia L3 (Android 8.1)
Shizuku method & Rooted
