### ISSUE TITLE
小窗应用优先级过高

### ISSUE THREAD

**Issue by Richard2091** [sunshine0523/Mi-Freeform#15]
使用小窗应用时，窗口的优先级高于其他所有界面，包括通知栏和其他悬浮窗。
个人感觉这样导致遮挡，影响体验。
![Screenshot_20221221-195500_Lawnchair](https://user-images.githubusercontent.com/53105011/208899924-acdd603f-9e4e-4c28-a358-f226db2f58a8.png)

**Comment by sunshine0523** [comment]
可以暂时通过使用前台服务的方式解决这个问题
