### ISSUE TITLE
米窗所有应用中打开应用不显示

### ISSUE THREAD

**Issue by gwc12412** [sunshine0523/Mi-FreeForm#2]
米窗所有应用中打开应用不显示，只显示一个透明窗口，如果把应用加入小窗应用列表才能正常打开，否则不能
机型：OnePlus 9 Pro
系统：OxygenOS；Android 12
版本号：LE2125_11_C.44
米窗版本：2.0.5 beta

**Comment by sunshine0523** [comment]
虽然已经过去很久了，但是还是回复一下，新版本已经修复了
