### ISSUE TITLE
小窗只支持单点触摸

### ISSUE THREAD

**Issue by theLIKImk** [sunshine0523/Mi-Freeform#22]
![Screenshot_20230228-231447_设置](https://user-images.githubusercontent.com/103368018/222032234-44c679fc-aa77-45b5-911e-d59ad3cb1ea0.png)
![Screenshot_20230228-231440_设置](https://user-images.githubusercontent.com/103368018/222032363-30e0f58b-1baf-457f-b140-a5f4206df695.png)

红色的线条是触摸位置，小窗内笔迹显示只检测一个触摸事件

（类原生ROM：Pixel Experience Plus，安卓13，机型RedmiK40）

**Comment by duzhaokun123** [comment]
装 [1.zip](https://github.com/sunshine0523/Mi-FreeForm/files/10857427/1.zip)

米窗打开 TouchDebug
测试多点触摸
发 log
