### ISSUE TITLE
功能性增强需求：设置某些应用优先在米窗应用前展示

### ISSUE THREAD

**Issue by greenhandzdl** [sunshine0523/Mi-FreeForm#27]
在米窗的使用中，例如gboard的输入法是在应用的底下出现，这样造成了打字不方便。
当然，这也只是几个具体例子之一，还是希望开发者能考虑下这个建议。

**Comment by sunshine0523** [comment]
记下了感谢

**Comment by sunshine0523** [comment]
米窗3新增了在小窗内展示输入法，也许可以暂时解决这个问题。在输入法之下展示小窗可能不现实，可能会做更加好的躲避输入法

**Comment by greenhandzdl** [comment]
但是还要你下滑系统的任务栏，小窗也还是显示在上面的啊…
