### ISSUE TITLE
开机后不会自启动

### ISSUE THREAD

**Issue by Gokou-Ruri** [sunshine0523/Mi-Freeform#3]
系统：DotOS 5.2.1 (Android 11)
环境：Shizuku 12.6 已授权
米窗：2.0.5 beta
每次开机后都需要手动打开米窗一次才能正常启动小窗，启动后不会掉后台，只是无法开机启动而已。

**Comment by gwc12412** [comment]
> 系统：Dot 2.1 (Android 5.11) 环境：Shizuku 12.6 已授权 米：2.0.5 beta 每次启动后都需要手动开启小窗，正常启动后不会掉窗，无法引导启动而已。

Android12 L一样

**Comment by enetec1** [comment]
Same on Moto Edge 30 Ultra Android 12
