### ISSUE TITLE
V3 wont start

### ISSUE THREAD

**Issue by aldesrahim** [sunshine0523/Mi-FreeForm#35]
Sorry, i know it is a "preview" release, but i am kinda curious for V3.. so i started install the mi freeform server zygisk using Magisk, but it keep says "service isn't running".

I've tried to turn the module on inside LSposed, but when device is restarted, the module got turned off.How do i properly install it and run it ?

Thank you

**Comment by sunshine0523** [comment]
Sorry. You can try preview v2. Coming soon.

**Comment by aldesrahim** [comment]
Oh, alright, thank you.
