### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by ghost** [sunshine0523/Mi-FreeForm#36]
With the latest Version 3.0.2 the App is installed but won't open and somehow doesn't occupy any storage. I've installed with Kernel SU. 
![Screenshot_20230911-095217_Evolution X Launcher](https://github.com/sunshine0523/Mi-Freeform/assets/101595090/d9d3e7da-bf5d-468d-ab03-84f0b4e9d199)
![Screenshot_20230911-095211_Settings](https://github.com/sunshine0523/Mi-Freeform/assets/101595090/6ebb0db1-8292-4d04-8fee-abe252d05909)
@sunshine0523  maybe have a look into it
![Screenshot_20230911-095257_KernelSU](https://github.com/sunshine0523/Mi-Freeform/assets/101595090/f715b9cf-289a-4d22-a8cb-da58d9a20f72)

**Comment by sunshine0523** [comment]
Maybe you can install app in module file by yourself
