### ISSUE TITLE
xml布局为google的cardview时，就会解析失败，但是用androidx的就可以的相关问题

### ISSUE THREAD

**Issue by Jesse205** [sunshine0523/Mi-FreeForm#37]
![image](https://github.com/sunshine0523/Mi-Freeform/assets/51242302/61856cd4-89ce-4338-a987-bea32c28878a)
![image](https://github.com/sunshine0523/Mi-Freeform/assets/51242302/21c37785-3d79-44e8-8159-307b9c3bcd6c)
![image](https://github.com/sunshine0523/Mi-Freeform/assets/51242302/701be280-3c12-40e6-adb2-11f728106fe1)
我注意到，您在初始化`FloatingWindow`的时候传入的是`applicationContext`

这个context没有主题，所以不是Material主题，所以会导致`MaterialCardView`无法初始化

**Comment by sunshine0523** [comment]
明白了！感谢
