### ISSUE TITLE
米窗导致“正在向已连接设备供电”

### ISSUE THREAD

**Issue by misaka19465** [sunshine0523/Mi-FreeForm#39]
在类原生系统（LineageOS 20）安装米窗3后，通知栏会出现“正在向已连接供电”通知，且连接PC后同时出现正在充电和正在向已连接供电，通过开关模块判断问题源于米窗。

KernelSU: v0.6.8
ZygiskOnKernelSU: v4-0.7.1
Device: Apollo

**Comment by sunshine0523** [comment]
可以暂时通过关闭米窗设置中的接管通知功能解决
