### ISSUE TITLE
3.0.5 preview

### ISSUE THREAD

**Issue by IamSingh01** [sunshine0523/Mi-FreeForm#43]
* The side bar doesn't always show up but the gesture still works.
* And the selected apps from the sidebar app also doesn't show up in the sidebar.
* setting button in rhe sidebar app won't response on the click.
* App list + floating app launches in the fullscreen.
* app list shows the same app multiple times.
* right most button under the floating screen doesn't work.. Others woros but not as responsive they should be.

App version - 3.0.5 preview
OS - Custom rom based on A13

![Screenshot_20231029-121527_Mi-Freeform](https://github.com/sunshine0523/Mi-Freeform/assets/31469965/09e2e49a-ed70-439f-8751-ee99f8833fb0)

**Comment by sunshine0523** [comment]
However. This screenshot is v3.0.4 or before version Mi-Freeform. v3.0.5`s view is not this. You can uninstall Mi-Freeform from Magisk and install new Mi-Freeform module.

**Comment by IamSingh01** [comment]
It's 3.0.5 only. I flashed the latest version. I didn't have 3.0.4 version flashed before this.

**Comment by sunshine0523** [comment]
I think I know why, and it will be fixed soon

**Comment by sunshine0523** [comment]
You can redownload Mi-Freeform magisk file from tag 3.0.5-preview. I delete old sidebar view. Remember new sidebar need Xposed.

**Comment by IamSingh01** [comment]
I did. 
![Screenshot_20231029-140253_Mi-Freeform - Sidebar](https://github.com/sunshine0523/Mi-Freeform/assets/31469965/18e667c9-6f78-481e-91e6-0f07bb68da37)
.Now the sidebar seems much usable but the sidebar still showing all the app in addition with the apps that I selected manually. 
And app list looks ugly. Icon size should be normal.
* Moreover, when the app is launched the floating screen is executed in the fullscreen and the content is huge as well.
* right most button still dead.
* 
![Screenshot_20231029-140442_Spotify](https://github.com/sunshine0523/Mi-Freeform/assets/31469965/53d84e00-34cb-4d33-9e16-875bb21cb0c2)
![Screenshot_20231029-140304_Lawnchair](https://github.com/sunshine0523/Mi-Freeform/assets/31469965/b81c349f-019a-4597-9c52-8bfc6ddc8932)

**Comment by sunshine0523** [comment]
Sidebar appearance issues will be optimized, and there will be many customization options.
The freeform size can be changed by setting the Mi-Freeform.
The button on the far right is the zoom button, which does not have any function when clicked
