### ISSUE TITLE
3.0版本开始不支持shizuku方式激活了吗？

### ISSUE THREAD

**Issue by xiufeiwu** [sunshine0523/Mi-FreeForm#47]
大神，手机暂时不能root，2.0系列版本用shizuku激活勉强能替代一些需求，期待更新版本的体验优化，发现没有单独的apk版本了，以后还会有支持么？

**Comment by sunshine0523** [comment]
暂时不确定，如果需要的人多会考虑

**Comment by J4gQBqqR** [comment]
求支持shizuku
HyperOS的解锁政策太恶心人了，没有达到等级根本没法用zip...

**Comment by ghost** [comment]
> 暂时不确定，如果需要的人多会考虑

求支持shizuku
HyperOS的解锁政策太恶心人了，没有达到等级根本没法用zip...

**Comment by PCL1234** [comment]
> 暂时不确定，如果需要的人多会考虑

求你了 加上吧
