### ISSUE TITLE
Won't redirect when clicked on links

### ISSUE THREAD

**Issue by singhh9596** [sunshine0523/Mi-FreeForm#6]
I've a little yet important concern from the start. Whenever I'm using some app, say I'm using gmail on floating window and I saw mail from github regarding an update of mi-freeForm and I click on that link nothing happens. I mean shouldn't it just launch the browser. 
But really appreciate the efforts for making this app. Specially the newer updates. It's working really flawlessly now.

**Comment by sunshine0523** [comment]
ok I'll check this out and get back to you here if there is any progress
