### ISSUE TITLE
Suggestion: Ability to change global sidebar position

### ISSUE THREAD

**Issue by likkai** [sunshine0523/Mi-FreeForm#8]
The current version only support changing the sidebar to the left or right of the screen. I hope there will be a new version which allows me to make it upper or lower. (Like how we change video toolbox position on miui by long pressing the sidebar and dragging it)

**Comment by sunshine0523** [comment]
I understand it!

**Comment by sunshine0523** [comment]
Mi-Freeform can change the sidebar upper&lower now. You can change it by sliding.
